### ISSUE TITLE
Installing npm packages with Meteor

### ISSUE THREAD

**Issue by erperejildo** [nmccready/google-maps-utility-library-v3-markerwithlabel#2]
I'm facing a problem installing the npm packages in my app when I run `meteor npm install`.
After this line I got some errors:
` fetchMetadata: verb cache add spec google-maps-utility-library-v3-markerwithlabel@git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git`
This is the first one:
```
git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git resetting remote C:\Users\Casa\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\.npm\_git-remote
s\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-535ad55b because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
```

Thanks in advance!

**Comment by nmccready** [comment]
Can you provide your package.json or meteor.json file. Sorry I am not too familiar with meteor.

**Comment by erperejildo** [comment]
this issue was created almost 1 year and a half ago. Not working on this anymore
