### ISSUE TITLE
git clone failing

### ISSUE THREAD

**Issue by psinkinson** [nmccready/google-maps-utility-library-v3-markerwithlabel#3]
Hi,

#### I'm opening this issue because:

"npm install" is failing to pull down github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git

#### What's going wrong?
We have a dependency on angular-google-maps (v 2.4.1). This package depends on github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git
on running npm install, the following error is being given : 
Cloning into bare repository '/Users/paul/.npm/_git-remotes/git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-535ad55b'...
npm ERR! fatal: read error: Connection reset by peer

We can still browse to https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel successfuly.
However attempts to clone the repo fail with the same "Connection reset by peer" error.

#### How can the CLI team reproduce the problem?

run:
git clone git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git

### supporting information:

running mac
Thanks you

Paul Sinkinson

**Comment by stephangrobler** [comment]
having the same issue, did you manage to fix it?

**Comment by nmccready** [comment]
#2 related

**Comment by nmccready** [comment]
```
{
  "name": "crap",
  "version": "0.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "google-maps-utility-library-v3-markerwithlabel": "git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git#1e1ae841596ce41fb5cfaff301477393c5621d3d"
  }
}

```

Seems to work fine. w both npm, and yarn

**Comment by nmccready** [comment]
If this is still an issue please chime in and I will re-open.
