### ISSUE TITLE
git clone failling 

### ISSUE THREAD

**Issue by ValdasDienas** [nmccready/google-maps-utility-library-v3-markerwithlabel#5]
Message:
      Failed to execute "git ls-remote --tags --heads git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git", exit code of #128
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by jperocho** [comment]
Yes I confirm, having the same issue.

**Comment by nmccready** [comment]
Wild, this would be a git or GitHub problem correct ? I have not changed the repo in forever .

**Comment by ValdasDienas** [comment]
Yes github made changes link https://github.blog/2021-09-01-improving-git-protocol-security-github/ 
Not correct 
git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git
correct way
https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git

**Comment by nmccready** [comment]
Ahh so regenerate your ssh keys please to use the supported encryption types. Then you can utilize ssh again.

**Comment by ValdasDienas** [comment]
The problem is that im using scaled build agents each time new machine is created its not possible for me generate keys automatically and add it to github

**Comment by nmccready** [comment]
You need to reconfigure how your build agent or CI process is setup . That is not covered in the scope of this project .

**Comment by ValdasDienas** [comment]
I added add ssh key to github but it doesnt work because the url should be different like below
git@github.com:nmccready/google-maps-utility-library-v3-markerwithlabel.git
not like this 
git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git

So input needed from you just change to https instead and all problems solved  
![image](https://user-images.githubusercontent.com/89068469/148953959-129bb775-7626-4b21-8213-864e99a7b549.png)

**Comment by ValdasDienas** [comment]
Git protocol troubleshooting
If you’re having trouble cloning a repository, make sure the URL starts with ssh://, https://, or git@github.com
For existing repositories, if you’re having trouble fetching, check that the remote you are fetching from is an ssh:// or https:// URL, or an SSH pseudo-URL starting with git@github.com. You can run git remote -v in the repository to see the URLs for all remotes. **If any of them start with git://, you should change the URL to a supported format.**
